Note that the CMAKE way of building medfichier is mainly provided for building a Windows version of med.
The CMAKE construction tool is also tested on Linux systems but for fairly simple configurations.
If you cannot build med-file with the CMAKE system, please test with the AUTOTOOL construction system.
In particular, cross compilation is not tested using the CMAKE construction system.
You can request CMAKE improvements but if a solution using the AUTOTOOL system exists, it will not be given high priority.

Thank you.
